FROM oven/bun:latest as base

FROM base AS build

RUN set -x \
  && bun add -g pnpm

WORKDIR /src

COPY . /src/

RUN set -x \
  && bun install \
  && bun run build

FROM base AS runner

WORKDIR /api

COPY --from=build --link --chown=1001:1001 /src/dist /api

EXPOSE 3000

ENV HOSTNAME=localhost