services:
  redis:
    image: redis:7.2-alpine
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 5000
    networks:
      - rinha-net
      - payment-processor
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api01: &api
    build:
      context: .
      dockerfile: ./Dockerfile-bun
    command: bun /api/index.js
    ports:
      - "9221:9229"
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "135MB"

  api02:
    <<: *api
    ports:
      - "9222:9229"

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - rinha-net
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge